spring.application.name=demo

spring.datasource.url=jdbc:mysql://database-1.c96g60smw793.us-east-2.rds.amazonaws.com:3306/todo_db
spring.datasource.username=admin
spring.datasource.password=RUIxiaorui1208!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379